
insert into kosan(nama, alamat, fasilitas, lintang, harga, sewa, jenis) value
('ABIMANYU KOST','Jalan Margasatwa Gang Abimanyu RT 02/05 Banaran','Kasur,  Meja,  Almari,  ','','Tahunan','Rp.4,000,000,-','Putra'),
('Airlines Homestay','Jl. Kalimasada 2 Ruko No. 3','Kasur,  Meja,  Kursi,  Almari,  TV bersama,  Dapur bersama,  ','','Tahunan','Rp.4,500,000,-','Putri'),
('Amalia 2','Jl.Kalimasada 2 No.28B RT 04/05','Kasur,  Meja,  Almari,  ','','Tahunan','Rp.4,500,000,-','Putri'),
('area 21','jalan cempaka sari raya rt 3/rw1 no 9 ( depan burjo mamang 2 )','Kasur,  Meja,  Almari,  TV bersama,  ','','Bulanan','Rp.350,000,-','Putra'),
('AVIRA','Gang Dahlia Nomor 5 Banaran RT 03/04','Kasur,  Meja,  Almari,  TV bersama,  Kulkas bersama,  Dapur bersama,  ','','Tahunan','Rp.4,000,000,-','Putri'),
('Cendekia','Jl.Kalimasada 1 RT/RW 04/05, Banaran','Kasur,  Meja,  ','','Tahunan','Rp.4,300,000,-','Putri'),
('Cendekia 2','Jl.Kalimasada Gg.Abimanyu RT/RW 08/05','Kasur,  Meja,  Kursi,  Almari,  TV bersama,  Kulkas bersama,  ','','Tahunan','Rp.4,000,000,-','Putri'),
('Delima 1','Jalan Taman Siswa Nomor 44 RT 02/04','Kasur,  Meja,  Almari,  TV bersama,  Kulkas bersama,  ','','Tahunan','Rp.5,000,000,-','Putri'),
('Delima 2','Jalan Taman Siswa Nomor 44 RT 02/04','Kasur,  Meja,  Almari,  TV bersama,  Kulkas bersama,  ','','Tahunan','Rp.4,500,000,-','Putri'),
('Deta hozz','Jalan taman siswa, gang rambutan no.36, sekaran unnes (belakang indoma','Kasur,  Meja,  Kursi,  Almari,  Dapur bersama,  ','','Tahunan','Rp.5,250,000,-','Putri'),
('Deta Kos Putri Kamar Mandi Dalam','Jalan Taman Siswa, Gang rambutan no.36, Belakang indomaret 15 meter','Kasur,  Meja,  Kursi,  Almari,  Kulkas bersama,  Dapur bersama,  ','','Tahunan','Rp.5,250,000,-','Putri'),
('Deta Kos Putri Kamar Murah','Jalan Taman Siswa, Gang rambutan no.36, sekaran, unnes. (belakang indo','Kasur,  Meja,  Almari,  Kulkas bersama,  Dapur bersama,  ','','Tahunan','Rp.2,500,000,-','Putri'),
('detahozz','jln. gang rambutan .no 36.sekaran .unnes . indomaret masuk . dpan salo','Kasur,  Meja,  Kursi,  Almari,  Kipas,  TV bersama,  Kulkas bersama,  Dapur bersama,  Mesin cuci bersama.','','Tahunan','Rp.5,250,000,-','Putri'),
('duanoe kost','jl.sekaran raya rt 2 rw 2(kiri jalan sebelum gang cempaka sari sesudah','Kasur,  Meja,  Kursi,  Almari,  Kipas,  TV bersama,  ','','Tahunan','Rp.4,000,000-','Putra'),
('Febriana','Jalan Taman Banaran Siswa Nomor 49 RT 02 RW 05 (sebelah buana futsal)','Kasur,  Meja,  Kursi,  Almari,  TV bersama,  Kulkas bersama,  Dapur bersama,  Mesin cuci bersama.','','Tahunan','Rp.5,000,000,-','Putri'),
('Febriana','Jalan Taman Siswa Banaran,Nomor 49 RT 02/05 (sebelah buana futsal)','Kasur,  Meja,  Kursi,  Almari,  TV bersama,  Kulkas bersama,  Dapur bersama,  Mesin cuci bersama.','','Tahunan','Rp.5,000,000,-','Putri'),
('Gendut','Jl taman siswa banaran no 55 rt 2/rw5','Kasur,  Meja,  Kursi,  Almari,  TV bersama,  Dapur bersama,  ','','Tahunan','Rp.3,500,000,-','Putri'),
('Gendut cost','Jl.taman siswa Banaran rt.2/rw.5 No.55','Kasur,  Meja,  Kursi,  Almari,  TV bersama,  Dapur bersama,  ','','Tahunan','Rp.3,000,000-','Putri'),
('Graha Annisa 1','Jl. Kalimasada 1 RT/RW 08/05, Banaran','Kasur,  Meja,  Kursi,  Almari,  TV bersama,  Kulkas bersama,  Dapur bersama,  ','','Tahunan','Rp.6,000,000,-','Putri'),
('Graha Annisa 2','Jl. Kalimasada RT/RW 02/05, Banaran','Kasur,  Meja,  Kursi,  Almari,  TV bersama,  Kulkas bersama,  Dapur bersama,  ','','Tahunan','Rp.6,500,000,-','Putri'),
('Graha Ena','Jl. Kalimasada RT.8 RW.5 Banaran, Sekaran','Kasur,  Meja,  Almari,  TV bersama,  Kulkas bersama,  Dapur bersama,  ','','Tahunan','Rp.6,000,000,-','Putri'),
('Graha Ena 1','Gg. Jeruk','Kasur,  Meja,  Almari,  TV bersama,  Dapur bersama,  ','','Tahunan','Rp.5,500,000,-','Putra'),
('Graha Ena 2','Gg. Cokro No. 6, Banaran','Kasur,  Meja,  Almari,  TV bersama,  Kulkas bersama,  Dapur bersama,  ','','Tahunan','Rp.6,500,000,-','Putri'),
('Graha Ena 3','Jl. Margasatwa RT.2 RW.5, Banaran','Kasur,  Meja,  Almari,  TV bersama,  Kulkas bersama,  Dapur bersama,  ','','Tahunan','Rp.6,000,000,-','Putri'),
('Green Kost','Gg Kantil No 25 RT 4 RW IV Kel Sekaran Gunung pati','Kasur,  Meja,  Kursi,  Almari,  TV bersama,  Dapur bersama,  ','','Tahunan','Rp.3,500,000,-','Putri'),
('Griya Bachri','Gang Nakula Nomor 22 RT 02 RW 05 Banaran','Kasur,  Meja,  Almari,  ','','Tahunan','Rp.3,500,000,-','Putra'),
('Griya Dua Putri','Gang Setanjung RT.03 RW.02 Sekaran Gunungpati Semarang','Kasur,  Meja,  Almari,  Kipas,  TV bersama,  Kulkas bersama,  Dapur bersama,  Mesin cuci bersama.','','Tahunan','Rp.8,000,000,-','Putri'),
('Griya Marista','Gg. Cempaka Sari Timur III Rt 03/01 Depan persewaan motor Aulia','Kasur,  Meja,  Almari,  Kulkas bersama,  Dapur bersama,  ','','Semesteran','Rp.2,100,000,-','Putri'),
('Griya Maulana 1','Jalan Pete Selatan 1 Perum Sekar Wangi no. 12A','','','Semesteran','Rp.3,000,000,-','Putra'),
('Griya Maulana 2','Jalan Cempaka Sari Perum Grand Sekar Wangi','Kasur,  Almari,  Dapur bersama,  ','','Tahunan','Rp.6,500,000,-','Putra'),
('Griya Narta Putri','Depan Dekanat FT, Kapling Cempakasari Timur, Sekaran, Gunungpati, Sema','','','Bulanan','Rp.400,000,-','Putri'),
('Griya Phalyta','Kelurahan Patemon Rt 02 Rw 02, Patemon','Kasur,  Meja,  Kursi,  Almari,  Kulkas bersama,  Dapur bersama,  ','','Tahunan','Rp.4,200,000,-','Putri'),
('Griya Phalyta','Kelurahan Patemon Rt 02 Rw 02, Patemon','Kasur,  Meja,  Kursi,  Almari,  Kulkas bersama,  Dapur bersama,  ','','Bulanan','Rp.400,000,-','Putri'),
('Griya Phalyta','Kelurahan Patemon Rt 02 Rw 02, Patemon','','','Semesteran','Rp.2,250,000,-','Putri'),
('Griya Phalyta','Dekat Kelurahan Patemon(dari Kelurahan Patemon belok kiri, lurus aja,','','','Bulanan','Rp.400,000,-','Putri'),
('GRIYA SATIVA','Sebelah fakultas hukum','','','Tahunan','Rp.7,000,000,-','Putri'),
('Griya Sinau','Jalan Cempaka Sari Nomor 33 RT 01/01, Sekaran','Kasur,  Meja,  Kursi,  Almari,  Kipas,  TV bersama,  Kulkas bersama,  Dapur bersama,  Mesin cuci bersama.','','Tahunan','Rp.7,000,000,-','Putri'),
('GRIYA TUAH CENDANA','Gang Cendana Barat RT 03/02 Sekaran','Kasur,  Meja,  Almari,  TV bersama,  Kulkas bersama,  ','','Tahunan','Rp.6,000,000,-','Putri'),
('GRIYA TUAH MUSTIKA','Jalan Taman Siswa Nomor 9 Belakang Soda Ocean','Kasur,  Meja,  Almari,  TV bersama,  Dapur bersama,  ','','Tahunan','Rp.7,250,000,-','Putri'),
('Griyo Argo','Banaran, RT 03/05 Gang Gatotkaca','Kasur,  Meja,  Almari,  Kipas,  ','','Tahunan','Rp.3,800,000,-','Putra'),
('Griyo Argo 2','Banaran RT 03/05 Gang Gatotkaca','Kasur,  Meja,  Almari,  Kipas,  ','','Bulanan','Rp.300,000,-','Putri'),
('Hanif Cost','Gang Cendrawasih RT 03 Rw 04 no 27 Patemon Gunungpati Semarang ( depan','Kasur,  Meja,  Almari,  TV bersama,  ','','Tahunan','Rp.3,250,000,-','Putra'),
('HOMEY Kos Putri','Perum Puspa Griya Sekaran: Jl.Pete Selatan RT 002/ RW 001 Kav 10, Seka','Kasur,  Meja,  Kursi,  Almari,  Kipas,  TV bersama,  Dapur bersama,  ','','Semesteran','Rp.2,400,000,-','Putri'),
('Idola Kost','Banaran RT04/04 Gg. Kantil','Kasur,  Meja,  Almari,  ','','Tahunan','Rp.4,000,000,-','Putra'),
('IRZA KOST','Jalan Cempaka Sari Timur 3 RT 03/01','Kasur,  Meja,  Almari,  TV bersama,  ','','Tahunan','Rp.4,000,000,-','Putra'),
('IRZA KOST 2','Jalan Cempaka Sari Timur 3 RT 03/01','Kasur,  Meja,  Almari,  TV bersama,  ','','Tahunan','Rp.4,500,000,-','Putra'),
('Kawulo Alit','Jl. Cempakasari 2 RT. 01/ RW. 01 No. 26 Sekaran','Kasur,  Meja,  Kursi,  Almari,  TV bersama,  Kulkas bersama,  Dapur bersama,  ','','Tahunan','Rp.4,000,000,-','Putri'),
('Kinanti 1A','Jalan Taman Siswa Nomor 50 RT 03/04 Banaran','Kasur,  Meja,  Kursi,  Almari,  TV bersama,  Kulkas bersama,  Dapur bersama,  ','','Tahunan','Rp.4,000,000,-','Putri'),
('Kontrakan putera Pak Aris','Gang Pete selatan rt 05 RW 08','Kasur,  Meja,  Almari,  ','','Tahunan','Rp.14,000,000,-','Putra'),
('Kos 99','Jalan Kol HR Hadijanto, Banaran RT03/RW V, Sekaran, Gunung Pati, Semar','Kasur,  Meja,  Almari,  TV bersama,  Dapur bersama,  ','','Bulanan','Rp.300,000,-','Putra'),
('Kos Alifirdaus (Mas Ali)','Gg.Dawung 2 RT/RW 01/04, Patemon (belakang Mas Pur 4)','Kasur,  Meja,  Almari,  Dapur bersama,  ','','Tahunan','Rp.3,500,000,-','Putri'),
('Kos Almaidah / Diva','Jalan Taman Siswa Banaran RT 01/05','Kasur,  Meja,  Kursi,  Almari,  TV bersama,  Kulkas bersama,  Dapur bersama,  ','','Tahunan','Rp.3,500,000,-','Putri'),
('Kos Bayu','jl.sekaran raya(kiri jalan dr unnes..sebelum gang Cempakasari','','','Tahunan','Rp.4,000,000,-','Putri'),
('Kos Berkah Putri','Gang waru Rt 3/2 Sekaran Gunungpati Semarang','Kasur,  Meja,  Almari,  Dapur bersama,  ','','Tahunan','Rp.9,000,000,-','Putri'),
('Kos Bu Astuti','Cempakasari Timur II, RT.03 RW.01 Sekaran','Kasur,  Meja,  Almari,  TV bersama,  ','','Tahunan','Rp.3,500,000,-','Putra'),
('Kos BU wahyu','Gang Pete selatan RT 05 RW 01','Kasur,  Meja,  Almari,  Dapur bersama,  ','','Tahunan','Rp.5,200,000,-','Putra'),
('Kos Cherry','Jalan Kalimasada Nomor 12A RT 07 RW 05 Banaran','Kasur,  Meja,  Almari,  TV bersama,  Kulkas bersama,  Dapur bersama,  ','','Tahunan','Rp.3,800,000,-','Putri'),
('Kos Depan Gerbang Unnes','Jl.Kol HR Hadijanto Blok B/7B kp.Banaran RT 005/IV (dpn gerbang UNNES)','Kasur,  Meja,  Almari,  TV bersama,  Kulkas bersama,  Dapur bersama,  ','','Tahunan','Rp.4,000,000,-','Putri'),
('Kos Ena Exclusive','Gang Margasatwa','Kasur,  Meja,  Kursi,  Almari,  Kulkas bersama,  Dapur bersama,  Mesin cuci bersama.','','Tahunan','Rp.12,500,000,-','Putri'),
('Kos Gang pisang belakang Unnes','Gang pisang belakang unnes','Kasur,  Meja,  Kursi,  Almari,  Kipas,  Dapur bersama,  ','','Bulanan','Rp.400,000,-','Putri'),
('Kos Ibu Koyimah','Jl. Kalimasada 1 No.24 RT/RW 04/05, Banaran','Kasur,  Meja,  Kursi,  Almari,  TV bersama,  Kulkas bersama,  ','','Tahunan','Rp.5,000,000,-','Putri'),
('Kos Imut','Jl. Margasatwa No.24, Banaran','Kasur,  Meja,  Almari,  ','','Tahunan','Rp.3,000,000,-','Putra'),
('Kos Lusito','Jl.Kalimasada 2 No.31B RT 04/05','Kasur,  Meja,  Almari,  ','','Tahunan','Rp.5,500,000,-','Putri'),
('KOS OASIS +WIFi','Jalan Banaran raya no.111 unnes','Kasur,  Meja,  Kursi,  Almari,  TV bersama,  Kulkas bersama,  Dapur bersama,  Mesin cuci bersama.','','Tahunan','Rp.3,700,000,-','Putri'),
('KOS PAK KAMSON','JALAN KALIMASADA GANG ARJUNA NO 6 BANARAN GUNUNG PATI SEMARANG','Kasur,  Meja,  Kursi,  Almari,  TV bersama,  Kulkas bersama,  Dapur bersama,  ','','Semesteran','Rp.1,750,000,-','Putri'),
('Kos Putri Griya Afika Unnes (Jl. Cempaka Sari 3 No.8)','Jl. Cempaka Sari 3 No. 8, Sekaran, Gunungpati, Semarang','Kasur,  Meja,  Almari,  TV bersama,  Kulkas bersama,  Dapur bersama,  ','','Tahunan','Rp.3,700,000,-','Putri'),
('Kos Rizkia','Jl. Taman Siswa Raya RT 01/05','Kasur,  Meja,  Almari,  ','','Tahunan','Rp.4,300,000,-','Putri'),
('Kos Rizkia','Gang Waru RT.02 RW.03 No.17 Sekaran Gunungpati Semarang','Kasur,  Meja,  Almari,  TV bersama,  Dapur bersama,  ','','Tahunan','Rp.5,000,000,-','Putri'),
('Kos Rizkia 2','Jalan Taman Siswa Raya Nomor 17','Kasur,  Meja,  Almari,  Dapur bersama,  ','','Tahunan','Rp.4,500,000,-','Putri'),
('Kos Srikandi 2','Jl. Kalimasada 2 RT/RW 04/05, Banaran','Kasur,  Meja,  Almari,  ','','Tahunan','Rp.5,500,000,-','Putri'),
('kos SSAE KOST Putri & Kost harian Keluarga','Jl.Cendrawasih Kav 14 Patemon Gunung Pati Semarang','Kasur,  Meja,  Almari,  ','','Semesteran','Rp.2,400,000,-','Putri'),
('Kos Toro 48','Jalan Kalimasada Gang Nakula no.48 Banaran','Kasur,  Meja,  Kursi,  Almari,  TV bersama,  Kulkas bersama,  Dapur bersama,  ','','Tahunan','Rp.4,000,000,-','Putri'),
('KOS VIESTA','Jalan Cempaka Sari Nomor 38 RT 02/02','Kasur,  Meja,  Kursi,  Almari,  TV bersama,  Kulkas bersama,  Dapur bersama,  ','','Tahunan','Rp.3,700,000,-','Putri'),
('KOS VIESTA 3','Jalan Cempaka Sari Nomor 38 RT 02/02','Kasur,  Meja,  Almari,  TV bersama,  ','','Tahunan','Rp.3,000,000,-','Putri'),
('KOS WULANDARI','Jalan Cempaka Sari Timur 1 RT 01/01','Kasur,  Meja,  Almari,  TV bersama,  Dapur bersama,  ','','Tahunan','Rp.3,500,000,-','Putri'),
('KOS WULANDARI 2','Jalan Cempaka Sari Timur 1 RT 01/01','Kasur,  Meja,  Kursi,  Almari,  ','','Tahunan','Rp.4,500,000,-','Putri'),
('Kos-kosan putra di pete raya','Jalan pete Raya','Kasur,  Almari,  TV bersama,  ','','Tahunan','Rp.3,500,000,-','Putra'),
('Kost Amanah','Jl.Margasatwa Gg.Abimanyu, Banaran','Kasur,  Meja,  Almari,  TV bersama,  Kulkas bersama,  ','','Tahunan','Rp.4,000,000,-','Putri'),
('Kost Ataya','Gang Kantil 3 Banaran rt 3 rw 4 Sekarang, Gunung Pati (UNNES-Fak. BAHA','Kasur,  Meja,  Almari,  TV bersama,  Kulkas bersama,  Dapur bersama,  Mesin cuci bersama.','','Tahunan','Rp.3,500,000,-','Putri'),
('Kost Putra Dan Putri Al Banat Sekaran Unnes','Sekaran, Kec. Gn. Pati, Kota Semarang, Jawa Tengah 50229','Kasur,  Meja,  Almari,  TV bersama,  ','','Tahunan','Rp.5,500,000,-','Putra'),
('Kost Putra Dan Putri Al Banat Sekaran Unnes','Jl. Taman Siswa, Gang Setanjung , Unnes, Sekaran, Patemon, Gunung Pati','Kasur,  Meja,  Kursi,  Almari,  TV bersama,  Dapur bersama,  ','','Tahunan','Rp.5,500,000,-','Putra'),
('Kost Putra Dan Putri Al Banat Sekaran Unnes','Sekaran, Kec. Gn. Pati, Kota Semarang, Jawa Tengah 50229','Kasur,  Meja,  Almari,  TV bersama,  ','','Tahunan','Rp.5,500,000,-','Putra'),
('Kost Putra Dan Putri Al Banat Sekaran Unnes','Jl. Taman Siswa, Gang Setanjung , Unnes, Sekaran, Patemon, Gunung Pati','Kasur,  Meja,  Kursi,  Almari,  TV bersama,  Dapur bersama,  ','','Tahunan','Rp.5,500,000,-','Putra'),
('Kost Samiaji','Jalan Cempaka Sari Nomor 14','Kasur,  Meja,  Kursi,  Almari,  TV bersama,  Dapur bersama,  ','','Tahunan','Rp.3,700,000,-','Putra'),
('Kost Tiara','Jl. Kalimasada Gg. Abimanyu II No 9B','Kasur,  Meja,  Almari,  TV bersama,  Kulkas bersama,  Dapur bersama,  ','','Tahunan','Rp.3,500,000,-','Putri'),
('KUSUMA SARI','Cempaka Sari Timur, Sekaran, Gunung pati, Sekaran','Kasur,  Meja,  Kursi,  Almari,  Kipas,  TV bersama,  Dapur bersama,  ','','Tahunan','Rp.5,500,000,-','Putri'),
('MAYUCHA','Jalan Margasatwa Gang Abimanyu','Kasur,  Meja,  Almari,  TV bersama,  ','','Tahunan','Rp.4,000,000,-','Putra'),
('Mnwr Kos','Jl. Taman Siswa No 61. RT02/05','Kasur,  Meja,  Kursi,  Almari,  TV bersama,  ','','Tahunan','Rp.3,700,000,-','Putra'),
('NEW BERLIN KOST','Jl. Cempaka 1 Sekaran','Kasur,  Meja,  Kursi,  Almari,  TV bersama,  Kulkas bersama,  Dapur bersama,  ','','Tahunan','Rp.4,500,000,-','Putri'),
('Nirwana Kos','Gang Kenanga Nomor 26 RT 04/04, Banaran, Sekaran','Kasur,  Meja,  Kursi,  Almari,  TV bersama,  Dapur bersama,  ','','Tahunan','Rp.4,400,000,-','Putri'),
('Prima Kos','Gang Pete Selatan RT.5 RW.1 Sekaran','Kasur,  Meja,  Almari,  Kipas,  TV bersama,  ','','Tahunan','Rp.3,500,000,-','Putra'),
('Roemah Kost Pelangi 1','Gang Cokro Nomor 13 RT 07/05','Kasur,  Meja,  Almari,  TV bersama,  Kulkas bersama,  Dapur bersama,  Mesin cuci bersama.','','Tahunan','Rp.4,200,000,-','Putri'),
('Roemah Kost Pelangi 2','Jl.Kalimasada RT/RW 04/05, Banaran','Kasur,  Meja,  Kursi,  Almari,  Kulkas bersama,  Dapur bersama,  Mesin cuci bersama.','','Tahunan','Rp.4,000,000,-','Putri'),
('Rumah Damai','Gang Kedawung 4, Patemon Semarang','Kasur,  Meja,  Almari,  Dapur bersama,  ','','Tahunan','Rp.3,600,000,-','Putra'),
('TERMURAH!!! GRIYA IJO KUNING','GANG KI AGENG GRIBIK BLOK C NO 12C BANARAN GUNUNGPATI (DEPAN GERBANG U','Kasur,  Almari,  TV bersama,  Dapur bersama,  ','','Tahunan','Rp.3,000,000,-','Putra'),
('Wisma Berkah','Jalan Cempaka Sari Timur 2 RT 03/01','Kasur,  Meja,  Almari,  TV bersama,  ','','Tahunan','Rp.3,500,000,-','Putra'),
('Wisma Berkah','Gang Cempakasari Timur','','','Tahunan','Rp.4,000,000,-','Putra'),
('Wisma Hapsari','Gg Pete raya rt 01/rw02 (masuk Gang depan MASPUR4, pertigaan NANAKYUT','Kasur,  Meja,  Almari,  TV bersama,  Kulkas bersama,  Dapur bersama,  Mesin cuci bersama.','','Tahunan','Rp.5,300,000,-','Putri'),
('Wisma Kita 1','Jalan Taman Siswa Nomor 44 RT 02/04','Kasur,  Meja,  Almari,  ','','Tahunan','Rp.4,500,000,-','Putri'),
('Wisma Kita 2','Jalan Taman Siswa Nomor 44 RT 02/04','Kasur,  Meja,  Almari,  ','','Tahunan','Rp.5,000,000,-','Putri'),
('Wisma Prabasari','Jl. Kalimasada 4 No 5 Banaran','Kasur,  Meja,  Almari,  ','','Tahunan','Rp.6,000,000,-','Putri'),
('Wisma Prabasari','Jl. Kalimasada 4 No 5 Banaran','','','Tahunan','Rp.6,000,000,-','Putri');

